all: weekly-totals weekly-totals-verified \
	daily-totals daily-totals-verified \
	hourly-totals hourly-totals-verified \
	named-clients-daily-totals \
	named-clients-hourly-totals \
	daily-deals-by-region \
	daily-deals-by-synthetic-region \
	daily-deals-by-country-state-province \
	daily-deals-by-synthetic-csp-region

clean: clean-weekly-totals clean-weekly-totals-verified \
	clean-daily-totals clean-daily-totals-verified \
	clean-hourly-totals clean-hourly-totals-verified \
	clean-named-clients-daily-totals \
	clean-named-clients-hourly-totals \
	clean-daily-deals-by-region \
	clean-daily-deals-by-synthetic-region \
	clean-daily-deals-by-country-state-province \
	clean-daily-deals-by-synthetic-csp-region


#
# weekly-totals
#

weekly-totals: $(WORK_DIR)/dist/deals/weekly-totals.json

$(WORK_DIR)/dist/deals/weekly-totals.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/aggr_weekly/json/windowStart=*/part-*.json)
	cat $(OUTPUT_DEALS_DIR)/deals/aggr_weekly/json/windowStart=*/part-*.json | \
		jq -s 'sort_by(.window.start)' > \
		$(WORK_DIR)/dist/deals/weekly-totals.json

clean-weekly-totals:
	rm -f $(WORK_DIR)/dist/deals/weekly-totals.json


#
# weekly-totals-verified
#

weekly-totals-verified: $(WORK_DIR)/dist/deals/weekly-totals-verified.json

$(WORK_DIR)/dist/deals/weekly-totals-verified.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_verified/aggr_weekly/json/windowStart=*/part-*.json)
	cat $(OUTPUT_DEALS_DIR)/deals/by_verified/aggr_weekly/json/windowStart=*/part-*.json | \
		jq -s 'sort_by(.window.start)' > \
		$(WORK_DIR)/dist/deals/weekly-totals-verified.json

clean-weekly-totals-verified:
	rm -f $(WORK_DIR)/dist/deals/weekly-totals-verified.json

#
# daily-totals
#

daily-totals: $(WORK_DIR)/dist/deals/daily-totals.json

$(WORK_DIR)/dist/deals/daily-totals.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/aggr_daily/json/date=*/part-*.json)
	cat $(OUTPUT_DEALS_DIR)/deals/aggr_daily/json/date=*/part-*.json | \
		jq -s 'sort_by(.window.start)[-14:]' > \
		$(WORK_DIR)/dist/deals/daily-totals.json

clean-daily-totals:
	rm -f $(WORK_DIR)/dist/deals/daily-totals.json


#
# daily-totals-verified
#

daily-totals-verified: $(WORK_DIR)/dist/deals/daily-totals-verified.json

$(WORK_DIR)/dist/deals/daily-totals-verified.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_verified/aggr_daily/json/date=*/part-*.json)
	cat $(OUTPUT_DEALS_DIR)/deals/by_verified/aggr_daily/json/date=*/part-*.json | \
		jq -s 'sort_by(.window.start)[-14:]' > \
		$(WORK_DIR)/dist/deals/daily-totals-verified.json

clean-daily-totals-verified:
	rm -f $(WORK_DIR)/dist/deals/daily-totals-verified.json

#
# daily-deals-by-region
#

daily-deals-by-region: $(WORK_DIR)/dist/deals/daily-deals-by-region.json

$(WORK_DIR)/dist/deals/daily-deals-by-region.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_miner_region/aggr_daily/json/part-*.json) $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_miner_region/sum_aggr_daily/json/part-*.json)
	node join-deals-by-region-daily.js by_miner_region > $@

clean-daily-deals-by-region:
	rm -f $(WORK_DIR)/dist/deals/daily-deals-by-region.json

#
# daily-deals-by-synthetic-region
#

daily-deals-by-synthetic-region: $(WORK_DIR)/dist/deals/daily-deals-by-synthetic-region.json

$(WORK_DIR)/dist/deals/daily-deals-by-synthetic-region.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_synthetic_region/aggr_daily/json/part-*.json) $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_synthetic_region/sum_aggr_daily/json/part-*.json)
	node join-deals-by-region-daily.js by_synthetic_region > $@

clean-daily-deals-by-synthetic-region:
	rm -f $(WORK_DIR)/dist/deals/daily-deals-by-synthetic-region.json

#
# daily-deals-by-country-state-province
#

daily-deals-by-country-state-province: $(WORK_DIR)/dist/deals/daily-deals-by-country-state-province.json

$(WORK_DIR)/dist/deals/daily-deals-by-country-state-province.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_provider_country_state_province/aggr_daily/json/part-*.json) $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_provider_country_state_province/sum_aggr_daily/json/part-*.json)
	node join-deals-by-region-daily.js by_provider_country_state_province > $@

clean-daily-deals-by-country-state-province:
	rm -f $(WORK_DIR)/dist/deals/daily-deals-by-country-state-province.json

#
# daily-deals-by-synthetic-csp-region
#

daily-deals-by-synthetic-csp-region: $(WORK_DIR)/dist/deals/daily-deals-by-synthetic-csp-region.json

$(WORK_DIR)/dist/deals/daily-deals-by-synthetic-csp-region.json: $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_synthetic_csp_region/aggr_daily/json/part-*.json) $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_synthetic_csp_region/sum_aggr_daily/json/part-*.json)
	node join-deals-by-region-daily.js by_synthetic_csp_region > $@

clean-daily-deals-by-synthetic-csp-region:
	rm -f $(WORK_DIR)/dist/deals/daily-deals-by-synthetic-csp-region.json

#
# hourly-totals
#

HOURLY_TOTALS_DATES_DIRS := $(wildcard $(OUTPUT_DEALS_DIR)/deals/aggr_hourly/json/date=*)
HOURLY_TOTALS_DATES := $(subst date=,,$(notdir $(HOURLY_TOTALS_DATES_DIRS)))
DIST_HOURLY_TOTALS := $(addsuffix .json,$(addprefix $(WORK_DIR)/dist/deals/hourly-totals/,$(HOURLY_TOTALS_DATES)))

hourly-totals: $(DIST_HOURLY_TOTALS) $(WORK_DIR)/dist/deals/hourly-totals/dates.json

$(WORK_DIR)/dist/deals/hourly-totals/dates.json: $(HOURLY_TOTALS_DATES_DIRS)
	(for f in $(HOURLY_TOTALS_DATES); do echo \"$$f\"; done) | jq -s 'sort' > $@

.SECONDEXPANSION:

$(DIST_HOURLY_TOTALS): $(WORK_DIR)/dist/deals/hourly-totals/%.json: $$(wildcard $(OUTPUT_DEALS_DIR)/deals/aggr_hourly/json/date=%/part-*.json)
	@echo $@
	@mkdir -p $(WORK_DIR)/dist/deals/hourly-totals
	@cat $^ | jq -s 'sort_by(.window.start)' > $@

clean-hourly-totals:
	rm -rf $(WORK_DIR)/dist/deals/hourly-totals

#
# hourly-totals-verified
#

HOURLY_TOTALS_VERIFIED_DATES_DIRS := $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_verified/aggr_hourly/json/date=*)
HOURLY_TOTALS_VERIFIED_DATES := $(subst date=,,$(notdir $(HOURLY_TOTALS_VERIFIED_DATES_DIRS)))
DIST_HOURLY_TOTALS_VERIFIED := $(addsuffix .json,$(addprefix $(WORK_DIR)/dist/deals/hourly-totals-verified/,$(HOURLY_TOTALS_VERIFIED_DATES)))

hourly-totals-verified: $(DIST_HOURLY_TOTALS_VERIFIED) $(WORK_DIR)/dist/deals/hourly-totals-verified/dates.json

$(WORK_DIR)/dist/deals/hourly-totals-verified/dates.json: $(HOURLY_TOTALS_VERIFIED_DATES_DIRS)
	(for f in $(HOURLY_TOTALS_VERIFIED_DATES); do echo \"$$f\"; done) | jq -s 'sort' > $@

.SECONDEXPANSION:

$(DIST_HOURLY_TOTALS_VERIFIED): $(WORK_DIR)/dist/deals/hourly-totals-verified/%.json: $$(wildcard $(OUTPUT_DEALS_DIR)/deals/by_verified/aggr_hourly/json/date=%/part-*.json)
	@echo $@
	@mkdir -p $(WORK_DIR)/dist/deals/hourly-totals-verified
	@cat $^ | jq -s 'sort_by(.window.start)' > $@

clean-hourly-totals-verified:
	rm -rf $(WORK_DIR)/dist/deals/hourly-totals-verified

#
# named clients: daily-totals
#

NAMED_CLIENTS_DAILY_TOTALS_DIRS := $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_client_name/aggr_daily/json/clientName=*)
NAMED_CLIENTS_NAMES := $(subst clientName=,,$(notdir $(NAMED_CLIENTS_DAILY_TOTALS_DIRS)))

DIST_NAMED_CLIENTS_DAILY_TOTALS := $(addsuffix /daily-totals.json,$(addprefix $(WORK_DIR)/dist/deals/named-clients/,$(NAMED_CLIENTS_NAMES)))

named-clients-daily-totals: $(DIST_NAMED_CLIENTS_DAILY_TOTALS) $(WORK_DIR)/dist/deals/named-clients/named-clients.json

$(WORK_DIR)/dist/deals/named-clients/named-clients.json: $(NAMED_CLIENTS_DAILY_TOTALS_DIRS)
	(for f in $(NAMED_CLIENTS_NAMES); do echo \"$$f\"; done) | jq -s 'sort' > $@

.SECONDEXPANSION:

$(DIST_NAMED_CLIENTS_DAILY_TOTALS): $(WORK_DIR)/dist/deals/named-clients/%/daily-totals.json: $$(wildcard $(OUTPUT_DEALS_DIR)/deals/by_client_name/aggr_daily/json/clientName=%/date*/part-*.json)
	@echo $@
	@mkdir -p $(dir $@)
	@cat $^ | jq -s 'sort_by(.window.start)' > $@

clean-named-client-daily-totals:
	rm -rf $(WORK_DIR)/dist/deals/named-clients/*/daily-totals.json

#
# named clients: hourly-totals
#

NAMED_CLIENTS_HOURLY_NAME_DIRS := $(wildcard $(OUTPUT_DEALS_DIR)/deals/by_client_name/aggr_hourly/json/clientName=*)
NAMED_CLIENTS_HOURLY_NAMES := $(subst clientName=,,$(notdir $(NAMED_CLIENTS_HOURLY_NAME_DIRS)))


DIST_NAMED_CLIENTS_DATES_JSON := $(addsuffix /hourly/dates.json,$(addprefix $(WORK_DIR)/dist/deals/named-clients/,$(NAMED_CLIENTS_HOURLY_NAMES)))

named-clients-hourly-totals: $(DIST_NAMED_CLIENTS_DATES_JSON)

.SECONDEXPANSION:

$(DIST_NAMED_CLIENTS_DATES_JSON): $(WORK_DIR)/dist/deals/named-clients/%/hourly/dates.json: $$(wildcard $(OUTPUT_DEALS_DIR)/deals/by_client_name/aggr_hourly/json/clientName=%/date*/part-*.json)
	@echo Make $@
	make -f Makefile.deals-named-clients named-clients-hourly-totals-worker NAMED_CLIENT=`echo $@ | sed 's,$(WORK_DIR)/dist/deals/named-clients/\([^/]*\)/hourly/dates.json,\1,'`

#
# Clean
# 

clean-named-client-hourly-totals:
	rm -rf $(WORK_DIR)/dist/deals/named-clients/*/hourly


